### ISSUE TITLE
Server config gone wrong?

### ISSUE THREAD

**Issue by sidvishnoi** [csdu/csdu.github.io#2]
![image](https://user-images.githubusercontent.com/8426945/68966670-aa672800-0804-11ea-8d52-9ef3f99c876e.png)

Was casually seeing old stuff. Seeing apache's default page on website. Intentionally down to save costs or some config gone bad? Would be better to redirect to default github.io site if under maintenance.

**Comment by jatin69** [comment]
We took down the server last year and redirected it to `github.io`. It was working fine until a week ago. we'll check it out.

**Comment by jatin69** [comment]
Just checked it out. Google's DNS had got corrupted. Restored it. 
The site shows okay in google panel. Github will soon update DNS and it should be up.

**Comment by jatin69** [comment]
Google's DNS had got corrupted. Restored it. The site's up now.
