### ISSUE TITLE
Links still show 2019

### ISSUE THREAD

**Issue by rumansaleem** [csdu/csdu.github.io#3]
"Sankalan 2019" link takes us to the coming soon page. This needs to be updated to link to the new website.

"Srijan 2019" link just need to be updated to say "Srijan 2020"

**Comment by sidvishnoi** [comment]
What happened to ducs.in? It's redirecting to GitHub org.

**Comment by jatin69** [comment]
I checked a few days ago, it wasn't pointed anywhere. So i pointed it to github. 
@rumansaleem feel free to update that.

Also minor update - i shifted the domain to a common ducs account - ducs.domain@gmail.com

**Comment by rumansaleem** [comment]
I have updated the ducs.in DNS records to point to GH Pages server. That's fixed now.

**Comment by ankushkhanna1998** [comment]
Issue is resolved by #4.
